---
abstract: authenticate human by create and validate captcha
author:
- Baskar Nallathambi <baskarmusiri@gmail.com>
dynamic_config: 0
license:
- perl_5
meta-spec:
  url: http://search.cpan.org/perldoc?CPAN::Meta::Spec
  version: '2'
name: Catalyst-TraitFor-Controller-CAPTCHA
prereqs:
  configure:
    requires:
      ExtUtils::MakeMaker: '6.30'
  runtime:
    requires:
      Moose::Role: '0'
      MooseX::MethodAttributes::Role: '0'
      namespace::autoclean: '0'
      GD::SecurityImage: '0'
      Catalyst::Plugin::Session: '0'
  test:
    requires:
      Catalyst: '0'
      Catalyst::Controller: '0'
      Catalyst::Runtime: '5.80'
      Catalyst::Plugin::Session: '0'
      Catalyst::Plugin::Session::Store::FastMmap: '0'
      Catalyst::Plugin::Session::State::Cookie: '0'
      FindBin: '0'
      Moose: '0'
      Test::More: '0'
      Test::WWW::Mechanize::Catalyst: '0'
      strict: '0'
      warnings: '0'
release_status: stable
resources:
  bugtracker:
    mailto: bug-Catalyst-TraitFor-Controller-CAPTCHA@rt.cpan.org
    web: http://rt.cpan.org/Public/Dist/Display.html?Name=Catalyst-TraitFor-Controller-CAPTCHA
  homepage: http://metacpan.org/release/Catalyst-TraitFor-Controller-CAPTCHA
  repository:
    type: git
    url: https://github.com/Virendrabaskar/Catalyst-TraitFor-Controller-CAPTCHA.git
    web: https://github.com/Virendrabaskar/Catalyst-TraitFor-Controller-CAPTCHA
version: '1.1'

